using InventoryAssignment.EntityFrameworkCore;
using Xunit;

namespace InventoryAssignment.EntityFrameworkCore;

public class InventoryAssignmentEntityFrameworkCoreCollectionFixtureBase : ICollectionFixture<InventoryAssignmentEntityFrameworkCoreFixture>
{

}
